version: '3.5'

services:
  postgres:
    image: ankane/pgvector:v0.4.4
    container_name: thing-assistant-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thing-assistant
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db:
    driver: local
