version: '3.5'
services:
  postgres:
    image: ankane/pgvector:v0.4.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file-assistant
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
    driver: local
