version: "3.5"

services:
  db:
    image: ankane/pgvector:v0.4.4
    container_name: thing-assistant-postgres
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  queue:
    image: redis:7.2.1-alpine
    container_name: thing-assistant-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - queue:/var/lib/redis/data

  backend:
    image: nest-backend
    container_name: thing-assistant-backend
    restart: unless-stopped
    command: ["yarn", "run", "start:dev"]
    depends_on:
      - db
      - queue
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
      - 8000:8000

volumes:
  db:
  queue:
