version: "3.5"

services:
  postgres:
    image: ankane/pgvector:v0.4.4
    container_name: thing-assistant-postgres
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: nest-backend
    container_name: thing-assistant-backend
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["yarn", "run", "start:dev"]
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
      - "8000:8000"
    restart: unless-stopped

  web:
    image: sveltekit-web
    container_name: thing-assistant-web
    depends_on:
      - backend
    build:
      context: ./web
      dockerfile: Dockerfile
    command: ["yarn", "run", "dev", "--host", "--port", "5000"]
    volumes:
      - ./web:/usr/src/app
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  db:
    driver: local
