version: '3.5'

services:
  postgres:
    image: ankane/pgvector:v0.4.4
    container_name: thing-assistant-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thing-assistant
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: nest-backend
    container_name: thing-assistant-backend
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'
      - '8000:8000'
    restart: unless-stopped

volumes:
  db:
    driver: local
