services:
  thing-assistant-postgres:
    image: ankane/pgvector:v0.4.4
    container_name: thing-assistant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  thing-assistant-backend:
    container_name: thing-assistant-backend
    restart: unless-stopped
    command: ["yarn", "run", "start:dev"]
    depends_on:
      - thing-assistant-postgres
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - COHERE_API_KEY=${COHERE_API_KEY}
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - ../backend:/usr/src/app

volumes:
  db:
