services:
  thing-assistant-postgres:
    image: ankane/pgvector:v0.4.4
    container_name: thing-assistant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  thing-assistant-backend:
    container_name: thing-assistant-backend
    restart: unless-stopped
    command: ["yarn", "run", "start:dev"]
    depends_on:
      - thing-assistant-postgres
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - WEB_URL=${WEB_URL:-*}
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - ../backend:/usr/src/app

  thing-assistant-web:
    container_name: thing-assistant-web
    restart: unless-stopped
    command: ["yarn", "run", "dev", "--host", "--port", "5000"]
    depends_on:
      - thing-assistant-backend
    build:
      context: ../web
      dockerfile: Dockerfile
    environment:
      - PUBLIC_API_URL=http://${BACKEND_IP:-localhost}:3000
      - PUBLIC_SOCKET_URL=http://${BACKEND_IP:-localhost}:8000
    ports:
      - 5000:5000
    volumes:
      - ../web:/usr/src/app

volumes:
  db:
