services:
  db:
    image: ankane/pgvector:v0.4.4
    container_name: thing-assistant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    image: nest-backend
    container_name: thing-assistant-backend
    restart: unless-stopped
    command: ["yarn", "run", "start:dev"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - COHERE_API_KEY=${COHERE_API_KEY}
    depends_on:
      - db
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
      - 8000:8000

volumes:
  db:
